name: Python CI

on:
  push:
    branches: [ "main", "dev", "uat" ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 openpyxl

    - name: Syntax check (py_compile)
      run: |
        python -m py_compile main.py
        python -m py_compile scheduler/*.py

    - name: Lint (flake8)
      run: |
        flake8 . \
          --count \
          --select=E9,F63,F7,F82 \
          --show-source \
          --statistics

    - name: Runtime smoke test
      run: |
        python main.py --year 2026 --month 2 --seed 1 --out test.xlsx
